import React, { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import FeaturesComponent from './../components/ProductFeatures';
import ProductDetailsHead from './../components/ProductDetailsHead';
import ProductList from './../components/ProductList';
import Reviews from './../components/Reviews';

const products = [
  {
    id: 1,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 2,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-02.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 3,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-03.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 4,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-04.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 5,
    name: 'Basic Tee',
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
    imageAlt: "Front of men's Basic Tee in black.",
    price: '$35',
    color: 'Black',
  },
  {
    id: 6,
    name: 'Product Name',
    price: '$69',
    rating: 4.9,
    reviewCount: 234,
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-quick-preview-02-detail.jpg',
    imageAlt: 'Image Alt Text',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.',
  }
  // More products...
];

const features = [
  {
    title: 'Chat Assist',
    description: 'Need to write something in a hurry? Just type a few keywords to achieve full productivity. Composer feature for Chat Assist requires a network connection and Samsung Account login. This feature is activated when a certain number of characters is met. Service availability may vary by language. Accuracy of results is not guaranteed.',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/bacf98d7-dfc0-4a43-ba4c-7e2e5746768e.__CR0,0,300,300_PT0_SX300_V1___.jpg',
  },
  {
    title: 'Browsing Assist',
    description: 'Find a website that you need to understand quickly? AI summarizes entire websites in a flash. Summary feature for Browsing Assist requires a network connection and Samsung Account login. Service availability may vary by language. Service may have limited functionality or unavailable on certain paid websites. Character limit applies. Accuracy of results is not guaranteed.',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/38645c58-5539-4b7e-8061-498bb5066a8f.__CR0,0,300,300_PT0_SX300_V1___.jpg',
  },
  {
    title: 'Photo Assist',
    description: 'Effortless editing, courtesy of Galaxy AI. With Photo Assist, just hold your finger down on an object to move, erase or enlarge it; adjust angles or fill backgrounds just as easily. Generative Edit feature for Photo Assist requires a network connection and Samsung Account login. Editing with Generative Edit may result in a resized photo up to 12MP. A visible watermark is overlaid on the image output upon saving in order to indicate that the image is generated by AI. The accuracy and reliability of the generated output is not guaranteed.',
    imageUrl: 'https://m.media-amazon.com/images/S/aplus-media-library-service-media/17a94716-b444-45b2-9d83-0d9c676e623a.__CR0,0,300,300_PT0_SX300_V1___.jpg',
  },
];

const ProductDetails = () => {
  const location = useLocation();
  const product = location.state?.product || {
    name: 'Default Product Name',
    price: '$69',
    rating: 4.9,
    reviewCount: 234,
    href: '#',
    imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-quick-preview-02-detail.jpg',
    imageAlt: 'Image Alt Text',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.',
  };
  
  const reviews = [
    {
      user: "Emily Selman",
      rating: 5,
      reviewText: "This is the bag of my dreams. I took it on my last vacation and was able to fit an absurd amount of snacks for the many long and hungry flights."
    },
    {
      user: "Hector Gibbons",
      rating: 3,
      reviewText: "Before getting the Ruck Snack, I struggled my whole life with pulverized snacks, endless crumbs, and other heartbreaking snack catastrophes. Now, I can stow my snacks with confidence and style!"
    },
    {
      user: "Mark Edwards",
      rating: 4,
      reviewText: "I love how versatile this bag is. It can hold anything ranging from cookies that come in trays to cookies that come in tins."
    }
  ];

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location]);

  return(
    <>
        <ProductDetailsHead product =  {product}/>
        <FeaturesComponent features = {features} />
        <Reviews reviews={reviews} />
        <ProductList products={products} />
        </>
  )
}
export default ProductDetails;